#### Filter by distribution

Erroneous or vagrant records were filtered by comparing to known distributions for taxa where distributions were available using the `filter_by_distribution` function in the envClean package `r cite_package("envClean")`. These distributions were sourced from: a) Environment Protection and Biodiveristy Conservation (EPBC) Act listings (https://fed.dcceew.gov.au/datasets/erin::australia-species-of-national-environmental-significance-distributions-public-grids-gdb/about), b) the Expert distributions layer for some South Australian taxa in EGIS (internal DEW dataset), c) Birds SA vetted distributions (https://birdssa.asn.au/distribution-maps/), and d) IUCN redlist (https://www.iucnredlist.org/resources/spatial-data-download for non-avian taxa; and BirdLife International for the redlist maps for avian taxa - https://datazone.birdlife.org/species/requestdis). For cases where taxa had a distribution in more than one source (e.g. EPBC and Redlist), distribution sources were ranked such that the most authoritative or fine-scaled were used over broader or less authoritative sources (i.e. 1) EPBC, 2) Expert, 3) Birds SA, 4) Redlist). Records were filtered if they were < `r settings$fbd_dist` km from the relevant known distribution.

`r paste0(clean_text$text[i], " ", clean_text$context_text[i])`