---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# envRas

The goal of envRas is to generate rasters for use in other projects, particularly: envEcosystems; and envSDMs.

# Background

## Satellite

A brief history of the satellite predict stack.

### First

* Used for ecosystems prior to ?2021
* Not generated by code
* South Australia + 50 km buffer

The first satellite predict stack was developed by TH. The stack was originally developed to inform rangeland condition assessments in about 2018, possibly earlier. They were all 30 m rasters that covered all of SA with a buffer of about 50 km. The satellite component used: a mix of Landsat and Sentinel; a mix of time periods; and also included a bunch of indices. There were about 45 layers in total from memory. These layers provided good predictions, thus they were definitely useful, However, there was not much documentation for most of them and due to the focus on rangeland condition the date ranges were specific to identifying parts of the rangelands that responded well after the millennium drought. It became problematic to explain the use of this predict stack as the date ranges become increasingly out dated and the lack of documentation.

### Second

* Used for ecosystems 2021/2022 ish
* Not generated by code
* South Australia + 50 km buffer

The second satellite predict stack used various TERN Landsat (and derived) products. There were downloaded from TERN and covered all of SA plus a 50 km buffer. These layers were used directly, plus a few derived indices that TH had made previously (but not all). While this second series were more easily documented, they did not perform as well as the first series, and they had many 'NA' issues - most salt lakes, beaches and often their immediate surrounds (plus various other areas) were given NA values in the original layers, leaving big holes in the resulting ecosystem maps.

### Third

* Used for ecosystems and SDMs 2023-2025
* Generated by previous [versions of envRas](https://github.com/dew-landscapes/envRas/tree/P120M--P3M__30)
* The outer extent of any IBRA Subregions or IMCRA provinces that intersect South Australia

The third satellite predict stack was based on Landsat [8](https://knowledge.dea.ga.gov.au/data/product/dea-surface-reflectance-nbart-landsat-8-oli-tirs/) & [9](https://knowledge.dea.ga.gov.au/data/product/dea-surface-reflectance-nbart-landsat-9-oli-tirs/) surface reflectance from Digital Earth Australia (plus five indices). These were created at both 90 m and 30 m grains, as seasonal medians for each summer and autumn 2015-2024, and then as a single (i.e. static), 10 year (15-24) seasonal median. This stack takes months to generate (especially the 30 m stack). These were used for both SDMs and ecosystems and perform OK, but some ecosystem runs suggest that some form of variation in a pixel's values is probably also required to better differentiate landcover types (thus requiring more months of data preparation). It is also hoped that fixing the problems noticed in the ecosystems runs with some form of variation will improve over-prediction / under-fitting in the SDMs.

There was also a consistently inconsistent issue with the generation of each season layer in which 0 to several chunks were 'lost' in the generation of the final layer. This left small windows of NA values across some of the seasonal individual year layers. (these are obviously different to dropping images due to too much cloud as images dropped due to cloud follow the 'diagonal' satellite swathe whereas the window of NA values were rectangular).

### Fourth

* Used from August 2025
* Generated by envRas
* Same extent as the third stack

The fourth satellite predict stack focused on:

* moving envRas to [targets](https://books.ropensci.org/targets/);
* reducing generation time;
* including a form of variation in the reflectance layers (rather than just using median values)

This fourth satellite predict stack uses the [DEA Geometric Median and Median Absolute Deviation](https://knowledge.dea.ga.gov.au/data/product/dea-geometric-median-and-median-absolute-deviation-landsat/) (or ga_ls8cls9c_gm_cyear_3), including three measures of variance "sdev", "edev" and "bcdev". The geometric median is meant to maintain relationships between reflectance layers, while generating a single value per pixel per calendar year. A nice side-effect of this approach is that the number of layers in the stack is 1 / 2 what it was previously (as they are not seasonal [summer and autumn]). All the measure of variability are multivariate (i.e. each variability layer provides a single measure of variance across all the reflectance layers), thus we don't need measures of variance per layer (further reducing the number of layers in the stack). They use dissimilarity measures to achieve this (cosine, Euclidean and Bray Curtis distances). A final big plus to this approach is that the entire satellite predict stack for the sa_br_dissolve extent will download in less than a day (instead of months). At 90 m it took roughly 10 minutes per reflectance band (integer) and 12 minutes per variability band (double). 30 m layers took just under an hour for the reflectance layers and 1 hr 10 for the variability layers. 

A few early outputs using the fourth satellite stack suggest it is not obviously worse than the third satellite stack - and with the enormous time saving it is likely here to stay for a while.

Unresolved issues with the fourth stack:

1) not sure how the move away from seasonal will effect the models. Had kept this through the second and third satellite predict stacks as TH found it useful and his layers were useful in predicting ecosystems.
1) unsure how spurious it is to take a (10 year) median of geometric medians and variance values.
1) indices are generated from the relevant 10 year median layers rather than calculated per pixel from the original layers as has been done previously. This is a massive saving in download time but not know sure how much it matters.
1) Interaction between 2) and 3) also unknown but probably not irrelevant.
1) The variability layers have 'issues' (striping where the satellite swathes overlap... presumably as there is more variability here due to different swathe timings)
1) Coastal aerosol is not available in ga_ls8cls9c_gm_cyear_3

