### PTP

In 2016 the Mount Lofty Ranges Paddock Tree Project (PTP) mapped properties in the eastern Mount Lofty Ranges as part of planning for planting of native overstorey species in that area. Each mapped area included a plant taxa list, including for each taxa a lifeform and cover estimate. This information exists in a range of reports generated by contractors but was considered important in helping to separate the continuum of cropping - improved pasture - native pasture - native grassland. Previous work highlighted difficulties in separating this continuum, particularly from improved pasture through to native grassland [e.g. @RN4461].

A geodatabase of mapped areas attributed with plant taxa and other associated information was generated from the information contained in reports. The polygon data was shoehorned into the other flora data by taking a point in each polygon at the furthest point from an edge and attributing that point with the taxa information.

The PTP was also able to provide cropping and pasture training points.

PTP data were imported to `R` using the `sf` package `r cite_package("sf")`.