```{r epoch{{this_layer}}}

  this_layerid <- "{{this_layer}}"

```

```{r epochData{{this_layer}}}

  layer_dat <- epoch_cube_data %>%
    dplyr::filter(layerid == this_layerid)

  this_layer <- unique(layer_dat$layer)
  this_desc <- unique(layer_dat$description)

  layer_sentence <- paste0(
    "There"
    , " "
    , if(nrow(layer_dat) > 1) "were" else "was"
    , " "
    , numbers2words(nrow(layer_dat))
    , " "
    , this_layer
    , " "
    , if(nrow(layer_dat) > 1) "layers" else "layer"
    , " in the epoch cube: \n\n* "
    , paste0(basename(layer_dat$path), collapse = "\n* ")
  )
  
```


### `r paste0(stringr::str_to_sentence(this_layer), ": ", this_desc)`

`r layer_sentence`

Figure \@ref(fig:epochHist{{this_layer}}) shows the distribution of values in each `r this_layer` layer. Figure \@ref(fig:epochMap{{this_layer}}) shows maps for each `r this_layer` layer.

```{r epochHist{{this_layer}}, fig.cap = paste0("Distribution of values in ", this_layer)}

  hist_data <- layer_dat %>%
    tidyr::unnest(cols = c(values))

  ggplot(hist_data, aes(values, fill = season)) +
    geom_density(alpha = 0.5
                 , colour = NA
                 ) +
    scale_fill_viridis_d() +
    theme(axis.text.y=element_blank()
          , axis.ticks.y=element_blank()
          ) +
    labs(y = "frequency"
         , x = this_layer
         )

```

```{r epochMap{{this_layer}}, fig.cap = paste0("Map of ", this_layer)}

  r <- epoch_cube[[grepl(paste0(this_layer, " "), names(epoch_cube))]]

  names(r) <- gsub(paste0(this_layer, " "), "", names(r))
  
  values(r) <- as.numeric(values(r))
  
  if(settings$level == "KI") {
    
    plot_extent <- terra::ext(r)
    plot_extent[4] <- 1610000
    plot_extent[3] <- 1540000 # exclude the islands a long way south of KI from the plots
    plot_extent[2] <- 1288000
    plot_extent[1] <- 1136000
    
    r <- terra::crop(r, y = plot_extent)
    
  }
     
  terra::panel(r
               , nc = if(unique(layer_dat$source) == "DEA") 1 else 2
               , buffer = FALSE
               )
              
```
